version: '3'

services:
  postgresql:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
      PGDATA: var/lib/postgresql/data/
    ports:
      - "54322:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data/

volumes:
  postgresql: